wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.2
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1704917321.653003
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 80
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 80
      3:
      - 2
      - 3
      - 8
      - 13
      - 23
      4: 3.8.10
      5: 0.16.2
      8:
      - 1
      - 5
      10:
      - 9
      13: linux-x86_64
