wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.1
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1704819793.944952
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 80
      3:
      - 23
      4: 3.8.10
      5: 0.16.1
      8:
      - 1
      - 5
      13: linux-x86_64
